name: portfol_io
description: My personal portfolio

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  web: ^1.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  get_it: ^7.2.0
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.1
  # responsive_framework: ^0.1.0
  responsive_builder: ^0.7.0
  flutter_command: ^5.0.0+17
  carousel_slider: ^5.1.1

  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1
  mailto: ^2.0.0
  overlay_support: ^2.0.1
  flutter_svg: ^2.0.5
  motion: ^1.4.0
  flutter_riverpod: ^2.3.4
  web_smooth_scroll: ^1.1.0
  shimmer: ^3.0.0
  pro_animated_blur: ^0.0.2+1
  flutter_improved_scrolling: ^0.0.3
  clipboard: ^0.1.3
  device_preview: ^1.1.0
  rive: ^0.13.1
  vector_math: ^2.2.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo1.png
    - assets/pic.jpeg
    - assets/avatar.png
    - assets/
    - assets/files/
    - assets/icons/
    - assets/images/
    - assets/images/work/
    - assets/images/work/cheesify/
    - assets/images/work/myo/
    - assets/images/work/penzmuzeum/
    - assets/images/work/barbr/
    - assets/images/work/ballerz/
    - assets/images/work/others/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
